spring:
  cloud:
    config:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false

server:
  servlet:
    context-path: /${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /manage

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF